-- ==========================================================
-- Generated by the dev.isaacudy.udytils.postgres Gradle plugin. Do not edit by hand.
-- ==========================================================

-- ----- Functions -----
CREATE OR REPLACE FUNCTION public.notify_poll_votes()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    PERFORM pg_notify('poll_votes', COALESCE(NEW.poll_id, OLD.poll_id));
    RETURN NULL;
END;
$function$

-- ----- Tables -----
CREATE TABLE deck_state (
    id integer NOT NULL,
    slide_id text NOT NULL,
    step integer NOT NULL,
    is_live boolean NOT NULL,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT deck_state_id_check CHECK (id = 1),
    CONSTRAINT deck_state_pkey PRIMARY KEY (id)
);

CREATE TABLE poll_votes (
    poll_id text NOT NULL,
    client_id text NOT NULL,
    option_id text NOT NULL,
    voted_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT poll_votes_pkey PRIMARY KEY (poll_id, client_id)
);

CREATE TABLE presenter_sessions (
    token_hash text NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT presenter_sessions_pkey PRIMARY KEY (token_hash)
);

CREATE TABLE questions (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    client_id text NOT NULL,
    text text NOT NULL,
    asked_at timestamp with time zone NOT NULL DEFAULT now(),
    hidden_at timestamp with time zone,
    CONSTRAINT questions_text_check CHECK (char_length(text) >= 1 AND char_length(text) <= 140),
    CONSTRAINT questions_pkey PRIMARY KEY (id)
);

CREATE TABLE reaction_totals (
    reaction text NOT NULL,
    total bigint NOT NULL,
    CONSTRAINT reaction_totals_pkey PRIMARY KEY (reaction)
);

-- ----- Indexes -----
CREATE INDEX questions_on_screen_by_asked_at ON public.questions USING btree (asked_at DESC) WHERE (hidden_at IS NULL);

-- ----- Triggers -----
CREATE TRIGGER poll_votes_notify AFTER INSERT OR DELETE OR UPDATE ON poll_votes FOR EACH ROW EXECUTE FUNCTION notify_poll_votes();

